---
# Go version to install
go_version: "1.24.2"

# Installation directory
go_install_dir: "/usr/local"

# System architecture (amd64, arm64, etc.) - will be auto-detected
go_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

# System OS
go_os: "linux"

# Go environment variables
go_env_vars:
  - "GOPATH=/home/{{ ansible_user_id }}/go"
  - "PATH=$PATH:{{ go_install_dir }}/go/bin:/home/{{ ansible_user_id }}/go/bin"

# Whether to download go every time
go_download_force: false